# Application Details
app_name: "dewy-app"
binary_port: 8080
container_port: 8081

# Dewy CLI Installation details
dewy_version: "2.14.1"

# GitHub settings (Used for GHCR/container mode)
github_owner: "sh0jitmy"
github_repo: "dewyctl"
ghcr_image: "ghcr.io/{{ github_owner }}/{{ github_repo }}"

# S3 / Sakura Object Storage settings (Used for binary mode)
s3_bucket: "your-bucket-name"
s3_prefix: "sample-app"
s3_endpoint: "https://s3.tky01.sakurastorage.jp"
s3_region: "jp-east-1"

# Deployment paths
app_binary_dest_dir: "/opt/{{ app_name }}"
